### ISSUE TITLE
dQdx hits contains all the hits on all the planes

### ISSUE THREAD

**Issue by nfoppiani** [soleti/ElectronNeutrinoSelection#5]
the branch shower_dQdx_hits is a vector (for each shower) of vectors, which contains the value of dQdx for each hit inside the boxes for each plane. 

I think it is better if we store three different variables, one for each plane.

**Comment by soleti** [comment]
Now in the `EnergyHelper::dQdx` method we store the hits for each plane in a vector of size 3. However, in the tree the analyzer stores at the moment only the collection plane hits, but new branches can be added if needed. The solution would be three-dimensional vectors, but ROOT has problems managing those last time I tried.
